config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  post "articles/new", to: "articles#create"
  get "draft", to: "articles#draft"
  resources :articles
  resources :issues
  post "issues/new", to: "issues#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  validates :title, presence: true
  # validate :not_before_now
  has_many_attached :images do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  def published?
    return true if is_published == true && post_reservation_date.nil?
  end

  # TODO: 日付に対するカスタムバリデーションを作成する
  # def not_before_now
  #   if post_reservation_date.present?
  #     if post_reservation_date <= Time.now
  #       errors.add(:post_reservation_date, "は過去の日時で指定できません")
  #     end
  #   end
  # end
end

app/models/issue.rb
class Issue < ApplicationRecord
  enum status: { unstarted: 0, in_progress: 1, completed: 2 }
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    redirect_to new_user_session_path unless user_signed_in?
  end

  def create
    @article = Article.new(article_params)

    # TODO: post_reservation_dateが現在時刻よりも前であればsaveさせない
    @article.is_published = false if @article.post_reservation_date.present?

    if params[:draft]
      @article.is_draft = true
      @article.is_published = false
    end

    if @article.save
      redirect_to @article
    else
      redirect_to new_article_path
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def draft
    @articles = Article.where(is_draft: true)
  end

  def index
    @articles = Article.all.with_rich_text_content.order(id: "DESC")
  end

  def edit
    redirect_to new_user_session_path unless user_signed_in?
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    # TODO: 公開中の記事はDRAFTボタンは表示させない
    if params[:draft]
      @article.is_draft = true
      @article.is_published = false
    end

    if params[:publish]
      @article.is_draft = false
      @article.is_published = true
    end

    if @article.update(article_params)
      @article.is_draft = false
      redirect_to @article
    else
      redirect_to edit_article_path(article)
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.delete
      redirect_to articles_path
    else
      redirect_to @article
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image, :is_draft, :is_published, :post_reservation_date, :published_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end


end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def new
    return if user_signed_in?

    redirect_to new_user_session_path
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to issues_path
    else
      redirect_to new_issue_path
    end
  end

  def edit
    redirect_to new_user_session_path unless user_signed_in?
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update(issue_params)
      redirect_to @issue
    else
      redirect_to edit_issue_path(issue)
    end
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def index
    @issues = Issue.all
  end

  def destroy
    @issue = Issue.find(params[:id])
    return unless @issue.destroy

    redirect_to issues_path
  end

  private

  def issue_params
    params.require(:issue).permit(:title, :content, :status)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/sign_in.html.erb
<h1>
  <%= form_with(model: @admin) do |form| %>

    <%= form.label :name, "NAME" %>
    <%= form.text_field :name %>

    <%= form.label :email, "EMAIL" %>
    <%= form.text_field :email %>

    <%= form.label :password, "PASSWORD" %>
    <%= form.text_field :password %>

    <%= form.submit "REGISTER" %>
  <% end %>
</h1>

app/views/articles/draft.html.erb
<h3 class="center-align">🙈</h3>
<div class="divider"></div>
<div class="container">
  <% @articles.each do |article| %>
    <% if article.is_draft %>
      <h5><b><%= link_to "#{article.title}", article %></b></h5>
      <%= article.created_at.strftime('%Y/%m/%d %H:%M') %>
      <% if current_user %>
        <%= link_to "編集", edit_article_path(article) %>
        <%= link_to "削除", article, method: :delete,  data: { confirm: "本当に削除しますか？" } %>
      <% else %>
        <%= "現在下書き中の記事はありません。"%>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h3 class="center-align">🔄</h3>

<%= form_with(model: @article, local: true, scope: :article) do |form| %>

  <div class="field">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>

    <%= form.label :content, "本文" %>
    <%= form.rich_text_area :content %>

    <div class="actions center-align">
    <% if @article.is_published == true && @article.is_draft == false %>
      <%= form.submit "UPDATE", class: "btn" %>
    <% elsif @article.is_published == false && @article.is_draft == true %>
      <%= form.submit "DRAFT", class: "btn", name: "draft" %>
      <%= form.submit "PUBLISH", class: "btn", name: "publish" %>
    <% else %>
      <%= form.submit "UPDATE", class: "btn" %>
    <% end %>
    </div>
  </div>
<% end %>

app/views/articles/index.html.erb
<h3 class="center-align">📖</h3>
<div class="divider"></div>
<div class="container">
  <% if @articles.nil? %>
    <h3 class="center-align"><b><%= "執筆を待て！" %></b></h3>
  <% end %>
  <% @articles.each do |article| %>
    <% if article.published? %>
      <% if article.is_draft != true %>
      <h5><b><%= link_to "#{article.title}", article %></b></h5>
        <%= article.created_at.strftime('%Y/%m/%d %H:%M') %>
        <% if current_user %>
          <%= link_to "編集", edit_article_path(article) %>
          <%= link_to "削除", article, method: :delete,  data: { confirm: "本当に削除しますか？" } %>
        <% end %>
      <% end %>
  <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h3 class="center-align">🖋</h3>

<%= form_with(model: @article, local: true, scope: :article) do |form| %>

  <div class="field">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>

    <%= form.label :content, "本文" %>
    <%= form.rich_text_area :content %>

    <div class="actions center-align">
      <%= form.submit "投稿する", class: "btn", nane: "post" %>
      <%= form.submit "下書き保存", class: "btn", name: "draft" %>

    <div class="waves-effect waves-light btn modal-trigger" href="#modal1">予約投稿する</div>

    <div id="modal1" class="modal">
      <h4 class="modal-content">公開する日時を選択してください</h4>

      <div class="picker-area">
        <%= form.datetime_field :post_reservation_date, class: "picker-area datetime-local center-align"%>
      </div>

      <div class="modal-footer">
        <%= form.submit "選択した日時で公開する", class: "modal-close waves-effect waves-green btn" %>
      </div>

    </div>

    </div>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    $('.modal').modal();
  });
</script>

app/views/articles/show.html.erb
<div class="center-align">
  <h3><b><%= @article.title %></b></h3>
  <%= @article.created_at.strftime('%Y/%m/%d %H:%M') %>
  <% if current_user %>
    <%= link_to "編集", edit_article_path(@article) %>
    <%= link_to "削除", @article, method: :delete, data: { confirm: "本当に削除しますか?" } %>
    <% if @article.post_reservation_date.present? %>
      <%= "現在未公開中です" %>
    <% end %>
    <% if @article.is_draft == true %>
      <%= "この記事は下書き保存中です" %>
    <% end %>
  <% end %>
</div>
<div class="divider"></div>

<p><%= @article.content %></p>
<% if @article.images.attached? %>
  <%= image_tag @article.image.variant(:display) %>
<% end %>

app/views/issues/edit.html.erb
<h3 class="center-align">🔄</h3>

<%= form_with(model: @issue, local: true, scope: :issue) do |form| %>

  <div class="field">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>

    <%= form.label :content, "詳細（任意）" %>
    <%= form.text_field :content %>

    <%= form.label :status, "ステータス" %>
    <div>
      <label>
        <%= form.radio_button :status, :unstarted %>
        <%= content_tag :span, 'unstarted' %>
      </label>
      <label>
        <%= form.radio_button :status, :in_progress %>
        <%= content_tag :span, 'in progress' %>
      </label>
      <label>
        <%= form.radio_button :status, :completed %>
        <%= content_tag :span, 'completed' %>
      </label>
    </div>

    <div class="actions center-align">
      <%= form.submit "UPDATE", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/issues/index.html.erb
<div class="center-align">
  <h3><b>🤔</b></h3>
  <% @issues.each do |issue| %>
    <% if issue.completed? %>
      <b>※Completedはすでに導入済みのissueです</b>
    <% end %>
  <% end %>
</div>
<!--TODO: checkboxを使った非同期検索を実装-->
  <!---<form action="#">

  <div class="container center-align">
    <div class="row">
      <label><input type="checkbox" checked="checked" /><span class="issue_statuses">Unstarted</span></label>
      <label><input type="checkbox" checked="checked" /><span class="issue_statuses">In Progress</span></label>
      <label><input type="checkbox" checked="checked" /><span class="issue_statuses">Completed</span></label>
    </div>
  </div>
  </form>--->

<div class="divider"></div>

<div class="container">

  <% if @issues.empty? %>
    <h5 class="center-align"><b><%= "今の所改善点が見当たらないみたいです.." %></b></h5>
  <% end %>

  <% @issues.each do |issue| %>
    <h5 class="blue-text"><b><%= "#{issue.title}" %></b></h5>
      <% if issue.status == "unstarted" %>
        <span class="blue white-text"><%= "😐" +  issue.status.titleize %></span>
      <% elsif issue.status == "in_progress" %>
        <span class="orange white-text"><%= "😤" +  issue.status.titleize %></span>
      <% else %>
        <span class="green white-text"><%= "🤩" + issue.status.titleize %></span>
      <% end %>

      <% if issue.content.present? %>
        <%= link_to "詳細", issue %>
      <% end %>
      <% if current_user %>
        <%= link_to "編集", edit_issue_path(issue) %>
        <%= link_to "削除", issue, method: :delete,  data: { confirm: "本当に削除しますか？" } %>
      <% end %>
  <% end %>
</div>

app/views/issues/new.html.erb
<h3 class="center-align">💭</h3>

<%= form_with(model: @issue, local: true, scope: :issue) do |form| %>

  <div class="field">
    <%= form.label :title, "タイトル" %>
    <%= form.text_field :title %>

    <%= form.label :content, "詳細(任意)" %>
    <%= form.text_field :content %>

    <%= form.label :status, "ステータス" %>
    <div>
      <label>
        <%= form.radio_button :status, :unstarted, class: "with-gap" %>
        <%= content_tag :span, 'unstarted' %>
      </label>
      <label>
        <%= form.radio_button :status, :in_progress, class: "with-gap" %>
        <%= content_tag :span, 'in progress' %>
      </label>
      <label>
        <%= form.radio_button :status, :completed, class: "with-gap" %>
        <%= content_tag :span, 'completed' %>
      </label>
    </div>

    <div class="actions center-align">
      <%= form.submit "CREATE", class: "btn" %>
    </div>

  </div>
<% end %>

app/views/issues/show.html.erb
<div class="center-align">
  <h3><b><%= @issue.title %></b></h3>
  <% if @issue.status == "unstarted" %>
    <span class="blue white-text"><%= "😐" +  @issue.status.titleize %></span>
  <% elsif @issue.status == "in_progress" %>
    <span class="orange white-text"><%= "😤" +  @issue.status.titleize %></span>
  <% else %>
    <span class="green white-text"><%= "🤩" + @issue.status.titleize %></span>
  <% end %>
  <% if current_user %>
    <%= link_to "編集", edit_issue_path(@issue) %>
    <%= link_to "削除", @issue, method: :delete,  data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</div>

<% if @issue.content.present?%>
  <div class="divider"></div>
  <p><%= @issue.content %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="center-align">
  <div class="divider"></div>
    <ul class="row">
      <li class="footer_logo col s3"><a href="https://github.com/bumpfuji10"><%= image_tag "github-mark.jpg" %></a></li>
      <li class="footer_logo col s3"><a href="https://twitter.com/bumpfuji10"><%= image_tag "twitter.jpg" %></a></li>
      <li class="footer_logo col s3"><a href="https://zenn.dev/yokamada_dev"><%= image_tag "zenn.jpg" %></a></li>
      <li class="footer_logo col s3"><a href="https://qiita.com/bumpfuji10"><%= image_tag "qiita.jpg" %></a></li>
    </ul>
    <p>© Yo Kamada 2022 - </p>
    <p>Build with <a href="https://rubyonrails.org/">Ruby on Rails</a> & <a href="https://materializecss.com/">Materialize</a></p>
</footer>

app/views/layouts/_header.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "記事を作る", new_article_path %></li>
  <li><%= link_to "issueを作る", new_issue_path %></li>
  <li class="divider"></li>
  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
</ul>
<nav class="teal">
  <div class="nav-wrapper">
    <a onclick="M.toast({html: 'ゆっくりしてけよ！'})" class="robot brand-logo right">🤖</a>
    <ul class="left">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Issues", issues_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Drafts", draft_path %></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% end %>
    </ul>
  </div>
</nav>
<script>
  $(".dropdown-trigger").dropdown();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kyam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h3 class="center-align">👋</h3>
<div class="col s12 m8 offset-m2 l6 offset-l3">
    <div class="row valign-wrapper">
      <div class="flex">
        <%= image_tag "me_avatar.jpg", class: "materialboxed circle me responsive-img" %>
      </div>
      <div class="flex">
        <div class="black-text">
          Webエンジニアをしている若輩者です。<br />
          このブログは知識のアウトプットと言語化をするための砂場として開発しました。<br />
          <!--TODO: URLをuuid化したときに修正必須-->
        </div>
      </div>
    </div>
</div>

<script>
  $(document).ready(function(){
    $('.materialboxed').materialbox();
  });
</script>